name: FriCAS CI on macOS on CLISP

on: workflow_dispatch
permissions: {}

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [macos-15-intel, macos-14]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      ARCH: ${{ matrix.os == 'macos-15-intel' && 'x86_64' || 'arm64' }}

    steps:
    - uses: actions/checkout@v4
    - name: download and install CLISP
      run: |
        brew update
        brew install clisp

    - name: configure
      run: |
        mkdir ../build && cd ../build
        ../fricas/configure --with-lisp=clisp || cat config.log

    - name: make
      run: cd ../build && make -j4

    - name: Create artifact archives
      run: |
        cd ../build
        make dist-macos
        ## reduce chance of error caused by "hdiutil: Resource busy"
        make dist-macos-dmg || make dist-macos-dmg
        mv FriCAS.dmg ../fricas/FriCAS-macOS-CLISP-${ARCH}-${{ github.sha }}.dmg

    - name: Upload macOS binary
      uses: actions/upload-artifact@v4
      with:
        name: FriCAS-macOS-CLISP-${{ env.ARCH }}-binary
        path: FriCAS-macOS-CLISP-${{ env.ARCH }}-${{ github.sha }}.dmg

    - name: make check
      run: cd ../build && make check -j4
