name: FriCAS CI on macOS

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-11
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: brew install sbcl gmp libx11 libxpm libice libsm
    - name: configure
      run: |
        mkdir ../build && cd ../build
        ../fricas/configure --with-lisp=sbcl --with-gmp --with-x=no || cat config.log
    - name: make
      run: cd ../build && make -j3
    - name: make check
      run: cd ../build && make check -j3
    - name: Create artifact archives
      run: |
        cd ../build && make dist-osx-dmg
        mv FriCAS.dmg ../fricas/FriCAS-macOS-x86_64-${{ github.sha }}.dmg
    - name: Upload macOS binary
      uses: actions/upload-artifact@v2
      with:
        name: FriCAS-macOS-x86_64-binary
        path: FriCAS-macOS-x86_64-${{ github.sha }}.dmg
    - name: Upload to nightly release
      if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/master' && github.repository == 'fricas/fricas' }}
      run: |
        export OWNER_REPO=fricas/fricas-nightly-builds
        export RELEASE_ID=`curl https://api.github.com/repos/${OWNER_REPO}/releases/tags/nightly | jq .id`
        curl -v -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.releasetoken }}" "https://uploads.github.com/repos/${OWNER_REPO}/releases/${RELEASE_ID}/assets?name=FriCAS-$(date +%Y-%m-%dT%H.%M)-macOS-x86_64-$(echo ${{ github.sha }} | cut -c 1-8).dmg" --data-binary "@FriCAS-macOS-x86_64-${{ github.sha }}.dmg" -H "Content-Type: application/x-apple-diskimage" || true
